export const FETCH_TODOS_INIT = 'FETCH_TODOS_INIT';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';



export const ADD_TODOS = 'ADD_TODOS';

export const DRAG_DROP_TODOS = 'DRAG_DROP_TODOS';

export const CHANGE_TARGET = 'CHANGE_TARGET';


